services:
  - type: web
    name: Laravel
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: base64:agWQBv26jmlrjMErAKHywLt+bS7V2jXfrfBxH7Xau3k=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3gjh02li9vc73f6f1u0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: vtab
      - key: DB_USERNAME
        value: vtab_user
      - key: DB_PASSWORD
        value: 8UXY42slLrN3v6JrebsbFMTbAeD6sWfg